# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 21:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20160922_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='interest_ignite',
            field=models.TextField(blank=True, help_text='Why are you here?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, help_text=b'Image suggested ratio: 3:2', upload_to=b'org'),
        ),
    ]
