# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170301_0502'),
        ('organizations', '0003_auto_20170130_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='interests',
            field=models.ManyToManyField(blank=True, to='profiles.Interest'),
        ),
        migrations.AddField(
            model_name='organization',
            name='interests_other',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
