# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20170303_0313'),
        ('testbeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbed',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Does this testbed belong to any program(s)?', to='programs.Program'),
        ),
    ]
