# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, max_length=500, null=True, upload_to=b'smart_gigabit')),
                ('pitch_video', models.URLField(blank=True, null=True)),
                ('pitch_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=b'smart_gigabit')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('google', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('link_text', models.CharField(default=b'LEARN MORE', max_length=50)),
            ],
            options={
                'ordering': ('order',),
                'verbose_name_plural': 'Pitches',
            },
        ),
    ]
