language: python
python:
  - "2.7"
services:
  - postgresql
env:
  - DJANGO=1.10.5 DB=mysql
install: "pip install -r requirements.txt"
before_script: # => 6

      - mysql -e 'create database test;' -u root
script: python manage.py test