# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 22:28


from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20141227_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='file',
            field=mezzanine.core.fields.FileField(max_length=200, upload_to='galleries', verbose_name='File'),
        ),
    ]
