# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 02:34


from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='body',
            field=mezzanine.core.fields.RichTextField(verbose_name='Body'),
        ),
    ]
