# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='LinkResource',
        ),
    ]
