# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 04:29


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomepageFeatured',
            new_name='HomepageFeaturedItem',
        ),
    ]
