# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_homepagefeatureditem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(2, 'Published'), (1, 'Draft'), (3, 'Removed')], default=1)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='homepagefeatureditem',
            name='status',
            field=models.IntegerField(choices=[(2, 'Published'), (1, 'Draft'), (3, 'Removed')], default=1),
        ),
    ]
