# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 08:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_auto_20170202_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeatureditem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepageprogram',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
