# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 02:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_auto_20170202_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sponsors')),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(2, 'Published'), (1, 'Draft'), (3, 'Removed')], default=1)),
            ],
        ),
    ]
