# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 02:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='title',
            new_name='name',
        ),
    ]
