# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:33


from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_auto_20170207_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=mezzanine.core.fields.FileField(max_length=255, verbose_name='File'),
        ),
    ]
