# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0010_auto_20170210_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagefeatureditem',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='homepagefeatureditem',
            name='the_order',
        ),
        migrations.AlterField(
            model_name='homepagefeatureditem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
