# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0011_auto_20170210_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageprogram',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
