# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 22:28


from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0013_auto_20170210_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=mezzanine.core.fields.FileField(max_length=255, upload_to='sponsor', verbose_name='File'),
        ),
    ]
