# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionclusters', '0003_auto_20170209_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncluster',
            name='category_keywords_string',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
