# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 00:54


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('actionclusters', '0005_auto_20170213_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncluster',
            name='site',
            field=models.ForeignKey(default='title', editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actioncluster',
            name='title',
            field=models.CharField(default='sdfds', max_length=500, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
