# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20170213_1911'),
        ('actionclusters', '0008_auto_20170213_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncluster',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Does this application belong to any specific program(s)', to='apps.Program'),
        ),
    ]
