# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:15


from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundingPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('image', mezzanine.core.fields.FileField(max_length=255, verbose_name='File')),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(2, 'Published'), (1, 'Draft'), (3, 'Removed')], default=1)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='File')),
                ('background_image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='File')),
                ('facts_background', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='File')),
                ('display_facts', models.BooleanField(default=True)),
                ('about_desc', models.TextField(blank=True, null=True, verbose_name='About description')),
                ('intro_desc', models.TextField(blank=True, null=True, verbose_name='Intro description')),
                ('application_terminology', models.CharField(default='application', max_length=255)),
                ('funding_agents', models.ManyToManyField(blank=True, to='programs.FundingPartner')),
                ('links', models.ManyToManyField(blank=True, to='programs.Link')),
            ],
        ),
    ]
