# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='links',
        ),
        migrations.AddField(
            model_name='link',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
            preserve_default=False,
        ),
    ]
