# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:58
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20170303_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
