# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20170303_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
