# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:36
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20170303_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='intro_desc',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Intro description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='about_desc',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='About description'),
        ),
    ]
