# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 22:28


from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20170303_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingpartner',
            name='image',
            field=mezzanine.core.fields.FileField(max_length=255, upload_to='galleries', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='program',
            name='background_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, upload_to='program', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='program',
            name='facts_background',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, upload_to='program', verbose_name='Facts Background'),
        ),
        migrations.AlterField(
            model_name='program',
            name='logo',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, upload_to='program', verbose_name='Logo'),
        ),
    ]
