# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_auto_20170305_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='accent_color',
            field=models.CharField(default='#EE7422', max_length=7),
        ),
    ]
