# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20170303_0313'),
        ('hubs', '0002_auto_20170130_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Does this community belongs to any programs?', to='programs.Program'),
        ),
    ]
