# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_auto_20170215_1739'),
        ('hubs', '0003_auto_20170215_1901'),
    ]

    operations = [
    ]
