# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 23:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.IntegerField(choices=[(0, 'I do not have any availability at this time'), (1, 'I have limited availability'), (2, 'I might be available'), (3, 'Yes, I would love to join a project')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Select image to use as avatar. If an image is not provided Gravatar will be used.', max_length=500, upload_to=b'avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quote',
            field=models.TextField(blank=True, help_text='Short quote.', max_length=140),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='What do you have to contribute? Design skills? Programming languages? Subject matter expertise? Project management experience?'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Please enter a URL starting with http or https', max_length=500),
        ),
    ]
