# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 00:11


from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170227_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Slug used for your profile. Recommended FirstName-LastName', populate_from=b'username', unique=True),
        ),
    ]
