# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20170304_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories_other',
            field=models.ManyToManyField(blank=True, related_name='profile_category_other', to='profiles.UserCategory', verbose_name='Other categories I associate with'),
        ),
    ]
