# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 23:39


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_auto_20170215_2339'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Does this resource belong to any specific program', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Program'),
        ),
    ]
