# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20170301_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.Sector'),
        ),
    ]
