# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20170123_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='tags',
            new_name='category_tags',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='domain',
            new_name='sector',
        ),
    ]
