# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 22:22


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20170124_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='position',
        ),
    ]
