# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 01:30


from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apps', '0007_auto_20170125_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_taggedcategory_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_tag', to='apps.AppTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedFunder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_taggedfunder_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder_tag', to='apps.AppTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='application',
            name='category_tags',
        ),
        migrations.RemoveField(
            model_name='application',
            name='funder_tags',
        ),
        migrations.AddField(
            model_name='application',
            name='category_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='apps.TaggedCategory', to='apps.AppTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='application',
            name='funder_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='apps.TaggedFunder', to='apps.AppTag', verbose_name='Tags'),
        ),
    ]
