# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 01:32
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20170125_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='apps.TaggedCategory', to='apps.AppTag', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='application',
            name='funder_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='apps.TaggedFunder', to='apps.AppTag', verbose_name='Funders'),
        ),
    ]
