# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20170125_0132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domain',
            new_name='Sector',
        ),
    ]
