# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20170125_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Idea Complete'), (2, 'Prototype Complete'), (3, 'In Development'), (4, 'Deployed'), (5, 'Commercialized')], default=1, help_text='Please select the option that best reflects your current progress.', verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Idea Complete'), (2, 'Prototype Complete'), (3, 'In Development'), (4, 'Deployed'), (5, 'Commercialized')], default=1, help_text='Please select the option that best reflects your current progress.', verbose_name='Stage'),
        ),
    ]
