# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 05:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20170209_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category_keywords_string',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='category_keywords_string',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
