# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 00:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20170210_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
