# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20170213_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='_meta_title',
        ),
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='keywords_string',
        ),
        migrations.RemoveField(
            model_name='application',
            name='site',
        ),
        migrations.RemoveField(
            model_name='application',
            name='title',
        ),
        migrations.RemoveField(
            model_name='applicationversion',
            name='_meta_title',
        ),
        migrations.RemoveField(
            model_name='applicationversion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='applicationversion',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='applicationversion',
            name='keywords_string',
        ),
        migrations.RemoveField(
            model_name='applicationversion',
            name='site',
        ),
        migrations.RemoveField(
            model_name='applicationversion',
            name='title',
        ),
    ]
