# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 01:51


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20170213_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='applicationversion',
            name='programs',
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Does this application belong to any specific program(s)', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Program'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Does this application belong to any specific program(s)', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Program'),
        ),
    ]
