# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:39


from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_auto_20170214_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
