# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:19


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_auto_20170215_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Year'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Year'),
        ),
    ]
