# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 19:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_auto_20170215_1908'),
        ('apps', '0019_auto_20170215_1739'),
    ]

    operations = [
    ]
