# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_auto_20170215_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='category_tags',
        ),
        migrations.RemoveField(
            model_name='application',
            name='funder_tags',
        ),
    ]
