# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_auto_20170215_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Does this application belong to any specific program', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Program'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Does this application belong to any specific program', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Program'),
        ),
    ]
