# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 00:58


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_merge_20170215_1926'),
        ('apps', '0024_auto_20170215_2339'),
    ]

    operations = [
    ]
