# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0006_auto_20170219_0216'),
        ('apps', '0025_merge_20170216_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hub',
            field=models.ForeignKey(blank=True, help_text='Does this application belong to a hub?', null=True, on_delete=django.db.models.deletion.CASCADE, to='hubs.Hub'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='hub',
            field=models.ForeignKey(blank=True, help_text='Does this application belong to a hub?', null=True, on_delete=django.db.models.deletion.CASCADE, to='hubs.Hub'),
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Does this application belong to any specific program?', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Program'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Does this application belong to any specific program?', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Program'),
        ),
    ]
