# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20150527_1555'),
        ('apps', '0026_auto_20170219_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='categories_test',
            field=models.ManyToManyField(blank=True, to='blog.BlogCategory', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='categories_test',
            field=models.ManyToManyField(blank=True, to='blog.BlogCategory', verbose_name='Categories'),
        ),
    ]
