# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_auto_20170301_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='categories_test',
        ),
        migrations.RemoveField(
            model_name='applicationversion',
            name='categories_test',
        ),
        migrations.AlterField(
            model_name='application',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.BlogCategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.BlogCategory', verbose_name='Categories'),
        ),
    ]
