# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 18:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_auto_20170303_0448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
