# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 22:28
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, upload_to='apps', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='applicationmedia',
            name='image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, upload_to='galleries', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, upload_to='apps', verbose_name='File'),
        ),
    ]
