# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_program_accent_color'),
        ('apps', '0031_auto_20170305_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='program_list', to='programs.Program', verbose_name='Programs'),
        ),
    ]
