# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_application_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='program_list', to='programs.Program', verbose_name='Does this application belong to any specific program(s)?'),
        ),
    ]
