# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 00:07
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_auto_20170306_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='default_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, upload_to='apps', verbose_name='Default Image'),
        ),
    ]
