# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_sector_default_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
