# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPost')),
                ('excerpt', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpost',),
        ),
    ]
