# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:11


from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20150527_1555'),
        ('apps', '0013_auto_20170209_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('status', models.IntegerField(choices=[(1, 'Published'), (2, 'Draft'), (3, 'Deleted')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPost')),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='File')),
                ('category_tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='apps.TaggedCategory', to='apps.AppTag', verbose_name='Categories')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpost',),
        ),
    ]
