# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170210_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='category_tags',
        ),
    ]
