# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170216_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='categories_new',
            field=models.ManyToManyField(blank=True, to='apps.Category', verbose_name='Categories'),
        ),
    ]
