# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170216_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='event',
            field=models.IntegerField(default=False),
        ),
    ]
