# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newspost_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='tags_string',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
