# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newspost_tags_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='tags_string',
        ),
    ]
