# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_newspost_tags_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='event',
            field=models.BooleanField(default=False),
        ),
    ]
