# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20170217_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='event',
            field=models.BooleanField(default=False, help_text='Is it an event?'),
        ),
    ]
