# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 07:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20170219_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
