# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:15


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newspost_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='categories_new',
        ),
    ]
