# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 22:28
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20170303_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, upload_to='blog', verbose_name='Image'),
        ),
    ]
